description: 33k PBMCs from a Healthy Donor
url: https://www.10xgenomics.com/datasets/33-k-pbm-cs-from-a-healthy-donor-1-standard-1-1-0

# data file URLs and names
adata_raw_url: https://caltech.box.com/shared/static/i0lb8vpiot1uvsolgdc6dbf3cqc4a3zv.h5  # custom
adata_raw_file_name: raw_feature_bc_matrix.h5  # automatically takes file name from adata_raw_url if provided
raw_tar_url: https://cf.10xgenomics.com/samples/cell-exp/1.1.0/pbmc33k/pbmc33k_raw_gene_bc_matrices.tar.gz
raw_tar_file_dir_suffix: null  # automatically detects if there is a single leaf path
filtered_tar_url: https://cf.10xgenomics.com/samples/cell-exp/1.1.0/pbmc33k/pbmc33k_filtered_gene_bc_matrices.tar.gz
filtered_tar_file_dir_suffix: null  # automatically detects if there is a single leaf path
sequencing_technology: 10XV2

# analysis parameters
model_pkl: Immune_All_High.pkl  # path, filename, or url for celltypist model pkl file
celltypist_convert: False
celltypist_map_file: null
cellsweep_max_iter: 2000
cellsweep_init_beta: 0.1
cellsweep_init_alpha: 0.9
cellbender_epochs: 150
cellbender_fpr: 0.01
cellbender_zdim: 64
cellbender_expected_cells: null
cellbender_total_droplets: null
scar_epochs: 200
scar_prob: 0.995
expected_cells: 33148
remove_empties: False
min_genes: 0
min_cells: 0
umi_top_percentile_to_remove: 5
fraction_doublet: 0
unique_genes_top_percentile_to_remove: 5
mt_gene_percentile_to_remove: 10
max_mt_percentage: null
n_top_genes: 2000
n_pcs: 25
n_neighbors: 20
leiden_resolution: 1.0
marker_genes: {
    "Monocytes": ["CD14", "LYZ", "FCGR3A", "MS4A7"],
    "Macrophages": ["CD68", "CD163", "C1QA", "C1QB", "C1QC"],
    "DC": ["CLEC9A", "XCR1", "CD1C", "FCER1A", "IL3RA", "TCF4", "ITGAX", "CST3"],
    "Neutrophils": ["S100A8", "S100A9", "MPO", "FCGR3B", "ELANE"],
    "Eosinophils": ["CLC", "RNASE2", "RNASE3", "PRG2"],
    "CD8 T cells": ["CD8A", "CD8B", "GZMB", "CD3E"],
    "CD4 T cells": ["CD4", "CCR7", "IL7R", "TCF7", "CD3E"],
    "NK cells": ["NKG7", "GNLY", "PRF1", "KLRD1", "GZMB"],
    "B cells": ["MS4A1", "CD79A", "CD79B", "HLA-DRA", "CD19"]
}
marker_genes_cellbender_fig2: {
    "Monocytes/neutrophils": ["S100A8", "S100A9"],
    "Monocytes/pDCs": ["LYZ", "CST3"],
    "(Broad expression)": ["PTPRC"]
}

# output file names
adata_path_cellsweep_name: pbmc33k_output_cellsweep.h5ad
adata_path_cellbender_name: pbmc33k_output_cellbender.h5
soupx_out_prefix_name: pbmc33k_output_soupx
decontx_out_prefix_name: pbmc33k_output_decontx
adata_path_scar_name: pbmc33k_output_scar.h5ad

# output file URLs from manuscript
cellsweep_matrix_url: https://caltech.box.com/shared/static/4vhgs34mft8ek8kym3e8i1auin68guto.h5ad
cellbender_matrix_filtered_url: https://caltech.box.com/shared/static/yslm0qf4j8ccmvdpukpv73wfx1dizqbf.h5
cellbender_ckpt_url: null
soupx_matrix_url: https://caltech.box.com/shared/static/62mfknok0lefmao77xggw4x76a8a9wsa.gz
decontx_matrix_url: https://caltech.box.com/shared/static/ifp3howd8dmb5n71yiun0r8d1czpau91.gz
scar_matrix_url: https://caltech.box.com/shared/static/0usrvy00ycyfbsbi1ko8x1ewb4t5m76s.h5ad

# how adata_raw_url was made``
# *run first few cells of benchmarking.ipynb - up to "Raw" cell*
# library(DropletUtils)
# library(Seurat)
# filter_matrix <- Read10X(raw_tar_file_dir)
# write10xCounts(adata_path_raw, filter_matrix, type = "HDF5", genome = "hg19", chemistry ="Single Cell 3' v2", version = "2", overwrite = TRUE, gene.id = rownames(filter_matrix), gene.symbol = rownames(filter_matrix))
