name: cellmender2
channels:
  - conda-forge
  - defaults
  - bioconda
  - r
dependencies:
  - python==3.10
  - pip
  - r-base
  - rpy2
  - r-soupx
  - bioconductor-decontx
  - bioconductor-singlecelltk
  - pip:
    - .[analysis]